### ISSUE TITLE
Set response limit?

### ISSUE THREAD

**Issue by MKBSoftware** [OpenXbox/xbox-webapi-python#19]
How can I set a response limit on a request? For example, I need all achievements from a game in one request without going to the next page.

**Comment by JBrame** [comment]
@BeLimitless I looked at the same thing myself, you can set the max number or records for the the underlying xbox api to return. I tried querying the API setting the number of records higher than what was currently being returned, and it was still limited to 32 records per page. So, I don't think it's possible due to a MS restriction.

**Comment by tuxuser** [comment]
Yea some endpoints have a maximum count of entries to return.
